floorplans:
  tasc1_8000.png:
    manual_alignment:
      rotx: 0.0
      roty: 0.0
      rotz: 0.11
      trax: 24
      tray: -13.5
      traz: 1.8
video:
  name: 'R0010228_er.MP4'
  delay: 0.3
  theta: true
