floorplans:
  tasc1_8000.png:
    manual_alignment:
      rotx: 0.0
      roty: 0.0
      rotz: -0.03
      trax: -58.25
      tray: -15.5
      traz: 1.8
video:
  name: 'R0010226_er.MP4'
  delay: 0.2
  theta: true
